"""Add state column to symbols table

Revision ID: c9c2c9e3dcb4
Revises: 
Create Date: 2025-04-29 00:29:57.362953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9c2c9e3dcb5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('symbols', sa.Column('state', sa.String(length=15), nullable=False, server_default='pause'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('symbols', 'state')
    op.drop_index(op.f('ix_orders_info_symbol_id'), table_name='orders_info')
    op.create_index('ix_order_info_symbol_id', 'orders_info', ['symbol_id'], unique=False)
    # ### end Alembic commands ###
